
# Allows for configuring the main zoom features.
[features]
	# "OFF": Disables the zoom's cinematic camera.
	# "VANILLA": Uses the game's cinematic camera while zooming.
	# "MULTIPLIED": Uses the cinematic camera with a configurable multiplier while zooming.
	# options: OFF, VANILLA, MULTIPLIED
	# default: OFF
	cinematic_camera = "MULTIPLIED"
	# Divides the mouse sensitivity with the zoom divisor while zooming.
	# default: true
	reduce_sensitivity = true
	# "OFF": The zoom will abruptly transition between its on and off states.
	# "SMOOTH": The zoom will smoothly transition between its on and off states in a manner resembling the game's FOV transitions.
	# "LINEAR": The zoom will linearly transition between its on and off states.
	# options: OFF, SMOOTH, LINEAR
	# default: SMOOTH
	zoom_transition = "SMOOTH"
	# Divides the amount of view bobbing with the zoom divisor while zooming.
	# default: true
	reduce_view_bobbing = true
	# "HOLD": The zoom will require the zoom key to be held.
	# "TOGGLE": The zoom will be toggled by the zoom key.
	# "PERSISTENT": The zoom will always be enabled, with the zoom key being used for zoom scrolling.
	# options: HOLD, TOGGLE, PERSISTENT
	# default: HOLD
	zoom_mode = "HOLD"
	# Allows to increase or decrease the zoom by scrolling with the mouse wheel.
	# default: true
	zoom_scrolling = true
	# Retains the interface when zooming.
	# default: false
	persistent_interface = false
	# Adds zoom manipulation keys along with the zoom key. A game reboot will be required in order to apply the changes.
	# default: true
	extra_key_binds = true
	# "OFF": Disables the zoom overlay.
	# "VIGNETTE": Uses a vignette as the zoom overlay. The vignette texture can be found at assets/ok_zoomer/textures/misc/zoom_overlay.png
	# "SPYGLASS": Uses the spyglass overlay as the zoom overlay.
	# options: OFF, VIGNETTE, SPYGLASS
	# default: OFF
	zoom_overlay = "SPYGLASS"
	# "OFF": Zooming won't require a spyglass and won't replace its zoom.
	# "REQUIRE_ITEM": Zooming will require a spyglass in order to work. This option is configurable through the ok_zoomer:zoom_dependencies item tag.
	# "REPLACE_ZOOM": Zooming will replace the spyglass zoom but it won't require one in order to work.
	# "BOTH": Zooming will act as a complete replacement of the spyglass zoom, requiring one to work and replacing its zoom as well.
	# options: OFF, REQUIRE_ITEM, REPLACE_ZOOM, BOTH
	# default: OFF
	spyglass_mode = "REQUIRE_ITEM"

# Allows for precise tweaking of the zoom.
[zoom_values]
	# The divisor used to apply zoom to the FOV. A higher value means more zoom.
	# range: 2.2250738585072014E-308 - 1.7976931348623157E308
	# default: 4.0
	zoom_divisor = 2.0
	# The minimum zoom divisor that you can scroll down.
	# range: 2.2250738585072014E-308 - 1.7976931348623157E308
	# default: 1.0
	minimum_zoom_divisor = 2.0
	# The maximum zoom divisor that you can scroll up.
	# range: 2.2250738585072014E-308 - 1.7976931348623157E308
	# default: 50.0
	maximum_zoom_divisor = 50.0
	# The number of steps between the zoom divisor and the minimum zoom divisor. Used by zoom scrolling.
	# range: 0 - 2147483647
	# default: 5
	lower_scroll_steps = 5
	# The number of steps between the zoom divisor and the maximum zoom divisor. Used by zoom scrolling.
	# range: 0 - 2147483647
	# default: 10
	upper_scroll_steps = 10
	# The multiplier used for the multiplied cinematic camera.
	# range: 2.2250738585072014E-308 - 32.0
	# default: 4.0
	cinematic_multiplier = 4.0

# Allows for precise tweaking of zoom transitions.
[transition_values]
	# The factor used for smooth zoom transitions. A lower value means a smoother transition, a higher value means a faster one.
	# range: 2.2250738585072014E-308 - 1.0
	# default: 0.6
	smooth_transition_factor = 0.5
	# The minimum value which the linear zoom transition step can reach.
	# range: 0.0 - 1.7976931348623157E308
	# default: 0.16
	minimum_linear_step = 0.16
	# The maximum value which the linear zoom transition step can reach.
	# range: 0.0 - 1.7976931348623157E308
	# default: 0.22
	maximum_linear_step = 0.22

# Provides a selection of unusual options.
[tweaks]
	# If pressed, the "Save Toolbar Activator" keybind will be unbound if there's a conflict with the zoom key.
	# default: true
	unbind_conflicting_key = false
	# Hides the crosshair while zooming.
	# default: true
	hide_crosshair = true
	# Allows for resetting the zoom with the middle mouse button.
	# default: true
	reset_zoom_with_mouse = true
	# If enabled, the current zoom divisor is forgotten once zooming is finished.
	# default: true
	forget_zoom_divisor = true
	# If enabled, the zoom will use spyglass sounds on zooming in and out.
	# default: false
	use_spyglass_sounds = true
	# Prints a random owo in the console when the game starts.
	# default: true
	print_owo_on_start = false

