# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
globalTooltip: false
noMicrosoftTelemetry: true
qol:
  suppressExperimentalSettingsWarning: true
  titleScreenNoFade: false
  hideDataComponentsTooltip: false
  loadingOverlayNoFade: false
debug:
  showTranslatedTagsByDefault: false
  tagsTooltip: false
  debugTooltipMsg: false
  tagsTooltipAppendKeybindHint: true
  tagsPerPage: 6
